# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79e2848683212d0109a88eeaf1317f5d2ceaa0a4738156ede01f128aea8e956413b2f6647f681ac83db8f6a814b230350982f7ede87388975047454c337c2b88

test:
  secret_key_base: a816097e505def40b75148fa4682c44bc1f62b1486af966c389aa3e3abfda8a9aec73a1fe49cbd49bf0e04f59434bdc8abf87e536dacea74c17421b1308a30fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
